version: "3.9"
services:
  # AUTHENTICATION SERVER
  keycloak_proxy:
    image: nginx:1.21.5
    container_name: keycloak_proxy
    ports:
      - "9443:9443"
    networks:
      - keycloak_frontend
    volumes:
      - ${CERTIFICATE_CRT_PATH}:/etc/authCertificate.key:ro
      - ${CERTIFICATE_KEY_PATH}:/etc/authCertificate.crt:ro
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: iriswebapp_authentication_keycloak
    environment:
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - DB_VENDOR=postgres
      - DB_ADDR
      - DB_USER
      - DB_PASSWORD
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      # The following file must only be passed to container when working on themes. Comment otherwise.
      # - ./keycloak/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli:ro
      - ./keycloak/themes/iris_custom:/opt/jboss/keycloak/themes/iris_custom:ro
    ports:
      - "8080:8080"
    networks:
      - keycloak_backend
      - keycloak_frontend

  keycloak_db:
    image: postgres:9.6.24
    container_name: keycloak_db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - keycloak_backend

networks:
  keycloak_backend:
    driver: bridge
  keycloak_frontend:
    driver: bridge
