version: "3.9"
services:
  # AUTHENTICATION SERVER
  keycloak_proxy:
    image: nginx:1.21.5
    container_name: keycloak_proxy
    ports:
      - "9443:9443"
    networks:
      - keycloak_frontend
    volumes:
      - ${CERTIFICATE_CRT_PATH}:/etc/authCertificate.key:ro
      - ${CERTIFICATE_KEY_PATH}:/etc/authCertificate.crt:ro
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: iriswebapp_authentication_keycloak
    environment:
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - DB_VENDOR=postgres
      - DB_ADDR
      - DB_USER
      - DB_PASSWORD
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
    networks:
      - keycloak_backend
      - keycloak_frontend

  keycloak_db:
    image: postgres:9.6.24
    container_name: keycloak_db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - keycloak_backend

  # AUTHENTICATION PROXY
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
    container_name: oauth2_proxy
    volumes:
      - ./proxy/oauth2-proxy_iris-web-app.cfg:/etc/oauth2-proxy.cfg:ro
      - ./certificates/irisAuthDev.key:/etc/authProxy.key:ro
      - ./certificates/irisAuthDev.crt:/etc/authProxy.crt:ro
      - ./rootCA/irisRootCACert.pem:/etc/rootCA.pem:ro
    command: oauth2-proxy --config=/etc/oauth2-proxy.cfg
    ports:
      - "4180:4180"
      - "4443:4433"
    extra_hosts:
      - "auth_iris.app.dev:172.17.0.1"
    networks:
      - test_app_network
      - app_network

  # TEST WEB APPLICATION
  test_web_application:
    image: nginx:1.21.5
    container_name: test_web_application
    volumes:
      - ./test_web_application/:/usr/share/nginx/html/:ro
      - ./test_web_application/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    networks:
      - test_app_network

networks:
  keycloak_backend:
    driver: bridge
  keycloak_frontend:
    driver: bridge
  test_app_network:
    driver: bridge
  app_network:
    external: true
    name: iris_frontend
